### ISSUE TITLE
Crash at 6/8 Identifying Speakers

### ISSUE THREAD

**Issue by binshe** [chidiwilliams/buzz#1314]
Latest CI build [Buzz-macOS-ARM64](https://github.com/chidiwilliams/buzz/actions/runs/20190941816/artifacts/4859123243) from https://github.com/chidiwilliams/buzz/actions/runs/20190941816

After transcribe task is done, in the identify speakers pop up, hit the Identify button and app crashes when progress shows 6/8 Identifying Speakers.

[buzz.log](https://github.com/user-attachments/files/24148912/buzz.log)

**Comment by raivisdejus** [comment]
@binshe Please check the [latest development version](https://chidiwilliams.github.io/buzz/docs/faq#9-where-can-i-get-latest-development-version) and if the issue persists See if you can get also [logs from the app](https://chidiwilliams.github.io/buzz/docs/faq#8-buzz-crashes-what-to-do) this is optional but may have some useful information

**Comment by binshe** [comment]
No crash this time, but resulted in Error. 

[logs.txt](https://github.com/user-attachments/files/24202226/logs.txt)

<img width="796" height="470" alt="Image" src="https://github.com/user-attachments/assets/94df93a0-673a-49c2-985c-288ab7ab1cbb" />

**Comment by raivisdejus** [comment]
@binshe Please try the latest development version. Should be fixed now

**Comment by binshe** [comment]
Stuck at step 3/8 . Please check [logs.txt](https://github.com/user-attachments/files/24285474/logs.txt)

**Comment by raivisdejus** [comment]
@binshe From the logs it seems there was some issue with your internet connection. I have added a retry feature where Buzz will try to use local models if they have already been downloaded. Internet connection will be required for the initial model download.

Please see the latest development build to see if this solves the issue

**Comment by binshe** [comment]
Still failed, twice.
Able to access https://huggingface.co/api/resolve-cache/models/MahmoudAshraf/mms-300m-1130-forced-aligner/2d856eb340893e274480dfb15a7b2a94d7ab7f84/config.json using browser.

[logs.txt](https://github.com/user-attachments/files/24323067/logs.txt)

<img width="1368" height="716" alt="Image" src="https://github.com/user-attachments/assets/2b59337e-ed74-4d8b-b5c7-cf1327a1c388" />

**Comment by raivisdejus** [comment]
@binshe Pushed a fix we used on some other places to solve issues with certificates. Please test if this has resolved the issues.

**Comment by BustosAndrew** [comment]
> [@binshe](https://github.com/binshe) Pushed a fix we used on some other places to solve issues with certificates. Please test if this has resolved the issues.

works fine for me on latest windows x64 build
